apply plugin: "java"

sourceSets.main.java.srcDirs = ["src"]

repositories {
    mavenCentral()

    ivy {
        url = 'https://github.com/'
        patternLayout {
            artifact '/[organisation]/[module]/releases/download/[revision]/dependencies.jar'
        }
        metadataSources { artifact() }
    }

    ivy {
        url = 'https://github.com/'
        patternLayout {
            artifact '/[organisation]/[module]/releases/[revision]/download/dependencies.jar'
        }
        metadataSources { artifact() }
    }

    ivy {
        url = 'https://github.com/'
        patternLayout {
            artifact '/[organisation]/[module]/releases/download/master/[revision].jar'
        }
        metadataSources { artifact() }
    }
}

java {
    targetCompatibility = JavaVersion.VERSION_17
    sourceCompatibility = JavaVersion.VERSION_17
}

ext {
    mindustryVersion = "v159.7"
}

dependencies {
    compileOnly "Anuken:Mindustry:$mindustryVersion"

    implementation "org.xerial:sqlite-jdbc:3.53.2.1"
}

jar {
    archiveFileName = "${project.name}.jar"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }

    from(rootDir) {
        include "plugin.json"
    }
}
